### ISSUE TITLE
Questions About Dataset Requirements for Relighting

### ISSUE THREAD

**Issue by HarryPeverell** [gsrelight/gs-relight#1]
First of all, thank you for the excellent work. It is truly inspiring.

I have a few questions:

Does the input dataset need to be an OLAT dataset? If the position of a new light source is known, is it possible to relight using a dataset obtained under static lighting conditions?

Is it feasible to perform relighting with a small OLAT dataset, such as 10 images?

Thank you for taking the time to read my questions. I look forward to your response.

Harry

**Comment by RupertPaoZ** [comment]
> First of all, thank you for the excellent work. It is truly inspiring.
> 
> I have a few questions:
> 
> Does the input dataset need to be an OLAT dataset? If the position of a new light source is known, is it possible to relight using a dataset obtained under static lighting conditions?
> 
> Is it feasible to perform relighting with a small OLAT dataset, such as 10 images?
> 
> Thank you for taking the time to read my questions. I look forward to your response.
> 
> Harry

Hello Harry, thank you for your interest in our work.

1. An OLAT input is indeed essential for our approach.
2. & 3. Using static lighting conditions or a small OLAT dataset (e.g., 10 images) may significantly impact the quality of relighting results.
Let me know if you have more questions or need further clarification!
