### ISSUE TITLE
Training freezes during shadow splatting

### ISSUE THREAD

**Issue by limacv** [gsrelight/gs-relight#2]
Hello! Thank you for making this amazing work publicly available! When I was playing this code base with my own OLAT data, I find that the training will freeze in certain iterations (sometimes the training stops with CUDA illegal memory access error). After debugging I identified that the program is stuck at the shadow splatting function `GaussianRasterizer_light`. Looking deeper into this function, I find that the CUDA code will run into some trouble if my training images that have resolutions not divisible by 32 (CUDA block resolution). A quick fix is to pad the resolution (and change fov accordingly) during shadow splatting such that the resolution matches the requirement. And this works good for me.

**Comment by joaxkal** [comment]
I also have this problem but regardless of resolution

**Comment by RupertPaoZ** [comment]
Thanks a lot! We have fix this bug in https://github.com/gsrelight/gs-relight/pull/5#issue-2670798209
