### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered during training

### ISSUE THREAD

**Issue by HarryPeverell** [gsrelight/gs-relight#4]
Hello, I'm encountering an issue during training, and I'd greatly appreciate any help or guidance from the community.

#### System Details:
- **Environment**: WSL 2 (Windows Subsystem for Linux)
- **GPU**: NVIDIA 4060 Ti
- **CUDA version**: CUDA 12.4
- **PyTorch version**: 2.4.1

#### Problem Description
When I run the training script (`bash real_train.sh`), the following error occurs after some initial training steps:

```
$ bash real_train.sh
Optimizing ./output/241203/real_scenes/Container
Output folder: ./output/241203/real_scenes/Container [12/11 16:18:38]
Use our shading function! [12/11 16:18:38]
Found transforms_train.json file, assuming Blender data set! [12/11 16:18:38]
json path:  /mnt/f/Dataset/OLAT/Container/Tower/Tower [12/11 16:18:38]
Reading Training Transforms [12/11 16:18:38]
100%|███████████████████████████████████████████████████████████████████| 2000/2000 [00:30<00:00, 66.53it/s]
Reading Test Transforms [12/11 16:19:08]
100%|█████████████████████████████████████████████████████████████████████| 400/400 [00:09<00:00, 44.43it/s]
Loading Training Cameras [12/11 16:19:18]
Loading Test Cameras [12/11 16:19:21]
Number of points at initialisation :  100000 [12/11 16:19:21]
Training progress:   0%|                                                         | 0/100000 [00:00<?, ?it/s]/home/harry/miniconda3/envs/gs3/lib/python3.10/site-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Training progress:   2%|▌                             | 2000/100000 [00:38<25:46, 63.35it/s, Loss=0.0565226]
[ITER 2000] Evaluating test: L1 0.018973999557783828 PSNR 23.583612933158875 [12/11 16:20:02]

[ITER 2000] Evaluating train: L1 0.01197401424869895 PSNR 24.967003250122072 [12/11 16:20:02]
Training progress:   4%|█                             | 3540/100000 [01:09<29:35, 54.33it/s, Loss=0.0498218]Traceback (most recent call last):
  File "/home/harry/gs-relight/train.py", line 319, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.unfreeze_iterations, args.debug_from)
  File "/home/harry/gs-relight/train.py", line 126, in training
    render_pkg = render(viewpoint_cam, gaussians, light_stream, calc_stream, local_axises, asg_scales, asg_axises, pipe, bg, fix_labert=True, is_train=prune_visibility)
  File "/home/harry/gs-relight/gaussian_renderer/__init__.py", line 168, in render
    assert not torch.isnan(shadow).any()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Training progress:   4%|█                             | 3540/100000 [01:10<31:47, 50.57it/s, Loss=0.0498218]
```

#### Steps I Have Taken to Debug
1. **Lowered `view_num` and Learning Rate**:
   - Reduced `--view_num` from 200 to 50 to reduce GPU memory usage.
   - Lowered learning rates (`asg_lr_init`, `local_q_lr_init`, etc.) to minimize numerical instability.

2. **Set Environment Variables**:
   - Set `CUDA_LAUNCH_BLOCKING=1` to force CUDA operations to be synchronous.

Despite these changes, I am still getting the same `CUDA illegal memory access` error.

#### Questions:
1. What could be causing this persistent illegal memory access error, even after reducing model complexity and learning rates?
2. Are there any known issues when using WSL for training models involving CUDA, and could that be related to my problem?
3. Would switching to a native Linux environment help, or are there other debugging steps I should take first?

Thank you in advance for any suggestions or insights!

**Comment by HarryPeverell** [comment]
The weird thing is that when I set `CUDA_LAUNCH_BLOCKING=1`, the CUDA operation is changed from asynchronous to synchronous, so there are no errors in the training.

**Comment by sjdfkjawe** [comment]
same error
/gs-relight/gaussian_renderer/__init__.py", line 168, in render
    assert not torch.isnan(shadow).any()
AssertionError

**Comment by RupertPaoZ** [comment]
> Hello, I'm encountering an issue during training, and I'd greatly appreciate any help or guidance from the community.
> 
> #### System Details:
> * **Environment**: WSL 2 (Windows Subsystem for Linux)
> * **GPU**: NVIDIA 4060 Ti
> * **CUDA version**: CUDA 12.4
> * **PyTorch version**: 2.4.1
> 
> #### Problem Description
> When I run the training script (`bash real_train.sh`), the following error occurs after some initial training steps:
> 
> ```
> $ bash real_train.sh
> Optimizing ./output/241203/real_scenes/Container
> Output folder: ./output/241203/real_scenes/Container [12/11 16:18:38]
> Use our shading function! [12/11 16:18:38]
> Found transforms_train.json file, assuming Blender data set! [12/11 16:18:38]
> json path:  /mnt/f/Dataset/OLAT/Container/Tower/Tower [12/11 16:18:38]
> Reading Training Transforms [12/11 16:18:38]
> 100%|███████████████████████████████████████████████████████████████████| 2000/2000 [00:30<00:00, 66.53it/s]
> Reading Test Transforms [12/11 16:19:08]
> 100%|█████████████████████████████████████████████████████████████████████| 400/400 [00:09<00:00, 44.43it/s]
> Loading Training Cameras [12/11 16:19:18]
> Loading Test Cameras [12/11 16:19:21]
> Number of points at initialisation :  100000 [12/11 16:19:21]
> Training progress:   0%|                                                         | 0/100000 [00:00<?, ?it/s]/home/harry/miniconda3/envs/gs3/lib/python3.10/site-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
> If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
>   warnings.warn(
> Training progress:   2%|▌                             | 2000/100000 [00:38<25:46, 63.35it/s, Loss=0.0565226]
> [ITER 2000] Evaluating test: L1 0.018973999557783828 PSNR 23.583612933158875 [12/11 16:20:02]
> 
> [ITER 2000] Evaluating train: L1 0.01197401424869895 PSNR 24.967003250122072 [12/11 16:20:02]
> Training progress:   4%|█                             | 3540/100000 [01:09<29:35, 54.33it/s, Loss=0.0498218]Traceback (most recent call last):
>   File "/home/harry/gs-relight/train.py", line 319, in <module>
>     training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.unfreeze_iterations, args.debug_from)
>   File "/home/harry/gs-relight/train.py", line 126, in training
>     render_pkg = render(viewpoint_cam, gaussians, light_stream, calc_stream, local_axises, asg_scales, asg_axises, pipe, bg, fix_labert=True, is_train=prune_visibility)
>   File "/home/harry/gs-relight/gaussian_renderer/__init__.py", line 168, in render
>     assert not torch.isnan(shadow).any()
> RuntimeError: CUDA error: an illegal memory access was encountered
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> Training progress:   4%|█                             | 3540/100000 [01:10<31:47, 50.57it/s, Loss=0.0498218]
> ```
> 
> #### Steps I Have Taken to Debug
> 1. **Lowered `view_num` and Learning Rate**:
>    
>    * Reduced `--view_num` from 200 to 50 to reduce GPU memory usage.
>    * Lowered learning rates (`asg_lr_init`, `local_q_lr_init`, etc.) to minimize numerical instability.
> 2. **Set Environment Variables**:
>    
>    * Set `CUDA_LAUNCH_BLOCKING=1` to force CUDA operations to be synchronous.
> 
> Despite these changes, I am still getting the same `CUDA illegal memory access` error.
> 
> #### Questions:
> 1. What could be causing this persistent illegal memory access error, even after reducing model complexity and learning rates?
> 2. Are there any known issues when using WSL for training models involving CUDA, and could that be related to my problem?
> 3. Would switching to a native Linux environment help, or are there other debugging steps I should take first?
> 
> Thank you in advance for any suggestions or insights!

This issue is caused by using GPU streams in Torch. Please ensure that there are no other programs running on the GPU you're using, or switch to running with a single stream. (Switch to `torch.cuda.current_stream()` at https://github.com/gsrelight/gs-relight/blob/4e949ed4fe0f53b04ff757b5041b7e690bb3af09/train.py#L67)

**Comment by HarryPeverell** [comment]
Thanks for your help !

**Comment by HarryPeverell** [comment]
Hi，
I modified the 67 and 68 behaviors in train according to your prompt:

`    light_stream = torch.cuda.current_stream()`
`    calc_stream =torch.cuda.current_stream()`

But there is still a chance that this error will trigger
```
[ITER 90000] Saving Checkpoint [03/12 04:52:06]
Training progress: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 100000/100000 [1:00:05<00:00, 27.74it/s, Loss=0.1988413]
Traceback (most recent call last):
  File "/home/harry/gs-relight/train.py", line 321, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.unfreeze_iterations, args.debug_from)
  File "/home/harry/gs-relight/train.py", line 168, in training
    training_report(tb_writer, iteration, Ll1, loss, l1_loss, iter_start.elapsed_time(iter_end), \
  File "/home/harry/gs-relight/train.py", line 273, in training_report
    render_pkg = renderFunc(viewpoint, scene.gaussians, light_stream, calc_stream, local_axises, asg_scales, asg_axises, *renderArgs)
  File "/home/harry/gs-relight/gaussian_renderer/__init__.py", line 168, in render
    assert not torch.isnan(shadow).any()
RuntimeError: CUDA error: an illegal instruction was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by RupertPaoZ** [comment]
> Hi， I modified the 67 and 68 behaviors in train according to your prompt:
> 
> ` light_stream = torch.cuda.current_stream()` ` calc_stream =torch.cuda.current_stream()`
> 
> But there is still a chance that this error will trigger
> 
> ```
> [ITER 90000] Saving Checkpoint [03/12 04:52:06]
> Training progress: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 100000/100000 [1:00:05<00:00, 27.74it/s, Loss=0.1988413]
> Traceback (most recent call last):
>   File "/home/harry/gs-relight/train.py", line 321, in <module>
>     training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.unfreeze_iterations, args.debug_from)
>   File "/home/harry/gs-relight/train.py", line 168, in training
>     training_report(tb_writer, iteration, Ll1, loss, l1_loss, iter_start.elapsed_time(iter_end), \
>   File "/home/harry/gs-relight/train.py", line 273, in training_report
>     render_pkg = renderFunc(viewpoint, scene.gaussians, light_stream, calc_stream, local_axises, asg_scales, asg_axises, *renderArgs)
>   File "/home/harry/gs-relight/gaussian_renderer/__init__.py", line 168, in render
>     assert not torch.isnan(shadow).any()
> RuntimeError: CUDA error: an illegal instruction was encountered
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> ```

Sorry for the delayed response. Occasionally, the `tinycudann` module may experience overflow issues due to its `fp16` implementation, leading to NaN values. You might want to consider using PyTorch as an alternative.
