### ISSUE TITLE
Question Regarding Shadow Splatting for Area and Parallel Light Sources

### ISSUE THREAD

**Issue by HarryPeverell** [gsrelight/gs-relight#6]
Hi ,

First of all, I would like to express my gratitude for the excellent work you've done on this project. It’s truly impressive, and I’ve found your approach to be very insightful.

I have a question regarding the dataset used in the project. It seems that the dataset is designed with point light sources in mind. I was wondering how the Shadow Splatting technique would be adapted if the light source were an area light source instead? Furthermore, if the light rays are parallel (as in the case of distant light sources or sunlight), how should the Shadow Splatting calculation be adjusted?

Could you please share the necessary modifications to the workflow for handling such changes in the light source? Any guidance on this would be greatly appreciated.

I look forward to your response, and thank you again for your great work.

Best regards,  
Harry

**Comment by RupertPaoZ** [comment]
You can simulate parallel light from infinity by using a directional light, such as modifying the camera model for the shadow splatting to an orthographic projection model, or directly using a point light source from a very distant location as an approximation.

**Comment by HarryPeverell** [comment]
Thank you very much for your previous response and assistance. Your guidance has been extremely helpful.

I have a new question regarding the adaptation of shadow splatting for directional light as described in the paper. Specifically, I would like to know the recommended approach to modify the code for orthographic projection to accommodate directional light.

Would it be sufficient to simply adjust the projection matrix in the current code, or are there additional considerations?

Here is the relevant code snippet:

```python
raster_settings_light = GaussianRasterizationSettings_light(
    image_height = int(viewpoint_camera.image_height),
    image_width = int(viewpoint_camera.image_width),
    tanfovx = tanfovx_far,
    tanfovy = tanfovy_far,
    bg = bg_color[:3],
    scale_modifier = scaling_modifier,
    viewmatrix = world_view_transform_light,
    projmatrix = full_proj_transform_light,
    sh_degree = pc.active_sh_degree,
    campos = viewpoint_camera.pl_pos[0],
    prefiltered = False,
    debug = pipe.debug,
)
```

I would greatly appreciate your insights and recommendations on this matter.

Thank you for your time and expertise.

Best regards,
Harry
